### PR TITLE
Update composer.json

### PR DESCRIPTION
**Pull request by aschempp**
The `symfony/*` dependencies are already part of `symfony/symfony`. `doctrine/annotations` is required by `contao/core-bundle`.

These changes are especially useful to prepare for the Contao Package Manager, because otherwise these will show up as "manageable" options but would have no effect.

### CODE REVIEW

**Comment by leofeyer** [comment]
`doctrine/annotations` is used [here](https://github.com/contao/standard-edition/blob/master/app/autoload.php#L11) and should therefore be required, shouldn't it?

**Comment by aschempp** [comment]
That's true, except if we would wrap that call into a `class_exists` to get rid of unnecessary dependencies…

**Comment by leofeyer** [comment]
It is not an unnecessary dependency and there is no reason to have different code than in the Symfony standard edition.

The difference to the Symfony standard edition is that they require `doctrine/doctrine-bundle`, which requires `doctrine/dbal`, which requires `doctrine/common`, which requires `doctrine/annotations`.

I wonder why we are not shipping the Doctrine bundle?

**Comment by aschempp** [comment]
Probably because we don't want ORM? But I'm pretty sure we do have DoctrineBundle, otherwise DBAL services would not be available…

**Comment by leofeyer** [comment]
I'm not talking about the core dependencies; we do require the Doctrine bundle there. However, Symfony requires it in the standard edition.

**Comment by aschempp** [comment]
Well imho the standard-edition should only require what it actually needs. But because we do configure the Doctrine bundle in our default configuration, we should probably require it…

**Comment by leofeyer** [comment]
> But because we do configure the Doctrine bundle in our default configuration, we should probably require it

I second that.

**Comment by leofeyer** [comment]
It seems I have already removed all the redundant requirements in the [develop branch](https://github.com/contao/standard-edition/blob/develop/composer.json). So the only thing left to do is to require `doctrine/doctrine-bundle` instead of `doctrine/annotations`.

**Comment by aschempp** [comment]
👍

**Comment by leofeyer** [comment]
Changed in facc90487661e314030238f87d7b63e40d0d5e60.

**Pull request closed without merging**
