### PR TITLE
[RTM] Add legacy packages repository to composer.json

### PR DESCRIPTION
**Pull request by aschempp**
Add the legacy packages repository to the standard edition as discussed at the dev meeting. This should only be merged once the composer plugin for Contao 4 is ready.

/cc @discordier

### CODE REVIEW

**Comment by aschempp** [comment]
Was this intentionally closed?

**Comment by leofeyer** [comment]
Yes, somehow. I have deleted the develop branch today, because we don't really need it for the standard-edition. You do not have to create another PR though. Just let me know when the Composer plugin for Contao 4 is ready.

**Comment by aschempp** [comment]
> because we don't really need it for the standard-edition

I disagree. The develop branch would be perfect for merging this PR (next feature release) ;-)

**Comment by discordier** [comment]
Having the repository available does not essentially depend on the plugin being ready. It would provide additional modules for search but none will be available for installing anyway as not marked compatible yet, let alone the dependency on the plugin not being satisfied yet.

On another note, will people really mark their extensions compatible with Contao in the old ER2?
I wonder if this is a good step as they should have started moving to "real" composer packages a long time ago. In the end this will always be superior over the version correcting hack we have in place in the legacy server as almost noone uses semver in ER2.

We should also discuss how many years we intend to keep the ER2 available for write access and how long for read only. At least for the 3.5 LTS phase is clear, but will we still run it afterwards?

**Comment by leofeyer** [comment]
> I wonder if this is a good step as they should have started moving to "real" composer packages a long time ago.

I very much agree with @discordier on this one.

**Comment by aschempp** [comment]
How do you intend to do that? With the current ER2? The current solutions works very well afaik?

**Comment by leofeyer** [comment]
Merged in 3a1c26821761d9889c316d60cbabfbbd2a507942.

**Pull request merged**
